# https://pub.dev/packages/pedantic_mono
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    sort_pub_dependencies: false
