name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/app
  - packages/design_system
  # - packages/common
  - packages/data
  - packages/domain
  # - packages/di

dev_dependencies:
  flutter_test:
    sdk: flutter
