name: domain
description: Domain layer of the Pokemon Breeder application.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  meta: ^1.12.0
  freezed_annotation: ^3.0.0
  
  # Riverpod for state management
  riverpod_annotation: ^2.3.4
  
  # Data layer dependency
  data:
    path: ../data

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^3.0.6
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  test: ^1.25.0
  
  # Riverpod code generation
  riverpod_generator: ^2.3.4
